// What each V0 check asserts. Names come from the bundle, so a check without an
// entry still renders under its raw name.

export const CHECKS: Record<string, string> = {
  run_json_present: "The run has a metadata record.",
  evidence_present: "The agent submitted an evidence bundle.",
  task_input_present: "The task the agent was given is on record.",
  evidence_parses: "The submission is readable JSON.",
  schema: "It matches the frozen evidence schema.",
  sample_id_matches: "The answer is for the sample that was asked.",
  clip_id_matches: "The answer is for the clip that was asked.",
  reported_count_matches_targets: "The reported count equals the number of listed targets.",
  abstain_shape: "An abstention lists no targets.",
  tamper_evidence_schema: "The evidence schema is unchanged since freeze.",
  tamper_experiment_config: "The experiment config is unchanged since freeze.",
  tamper_prompt: "The prompt is unchanged since freeze.",
  tamper_pi_sampling: "The sampling extension is unchanged since freeze.",
  tamper_v0: "This checker is unchanged since freeze.",
  tamper_enhanced: "The enhanced evaluator is unchanged since freeze.",
  tamper_policy: "The evaluator policy is unchanged since freeze.",
  tamper_tools: "The perception tools, which write the budget ledger, are unchanged since freeze.",
  frame_bounds: "Cited frame ids are inside the clip.",
  timestamp_alignment: "Cited timestamps agree with their frame ids.",
  roi_bounds: "Cited regions lie inside the frame.",
  intervals_valid: "Reported intervals are ordered and inside the clip.",
  artifact_refs_exist: "Every cited frame and observation file exists.",
  artifact_refs_run_owned: "Those files were produced by this run.",
  windows_valid: "Every window the agent says it examined is inside the clip.",
  budget: "No frame budget was exceeded.",
  budget_ledger_agrees: "The frame count the agent claimed matches the tools' own ledger.",
  tool_logs_present: "The instrumented tools wrote their logs.",
  agent_trace_present: "The harness's event log exists.",
  exit_status_recorded: "How the agent process ended is on record.",
  environment_snapshot: "The machine state was captured at launch.",
  service_refs: "The model servers are identified by id and revision.",
  seed_application_evidence: "The per-request agent seed reached the model request.",
  manifest_pre_run: "A pre-run manifest event was written before the agent launched.",
  run_dir_was_new: "The run wrote into a fresh directory, so no earlier result was overwritten.",
};
